[package]
name = "ecl-sys"
version = "0.1.0"
authors = ["Riey <creeper844@gmail.com>"]
edition = "2018"
links = "ecl"
build = "build.rs"
license = "MIT"
categories = ["external-ffi-bindings"]
description = "ECL bindings for Rust"

[dependencies]

[build-dependencies]
bindgen = "0.51.0"
